/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package competitive.programming.gradle.plugin;

import competitive.programming.models.Platform;
import competitive.programming.tasks.ProblemFileCreatorTask;
import competitive.programming.utils.Constants;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class CompetitiveProgrammingPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getExtensions().create("competitiveProgramming", CompetitiveProgrammingExtension.class);
        project.getTasks().register("initProblem", ProblemFileCreatorTask.class);
    }
}
